# Generated by Django 3.0.5 on 2020-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_pub_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='something'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_data',
            field=models.DateTimeField(default='something'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='something', max_length=255),
        ),
    ]
