# Generated by Django 3.0.5 on 2020-04-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200430_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_data',
            field=models.DateField(default='something'),
        ),
    ]
