# Generated by Django 3.0.5 on 2020-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200430_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_data',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM'),
        ),
    ]
